title: Sakib Hosen Himel
logo: /assets/img/Picture 1-modified.png
description: Aspiring Data Analyst
LinkdIn:
  another_url:  www.linkedin.com/in/sakib-hosen-himel-3867a023a
show_downloads: false
theme: jekyll-theme-leap-day
